pass:
	g++ -Wall -Werror -std=c++17 -g *.cpp *.h -o lab5
	./lab5 in50.txt > ans.txt && diff out50.txt ans.txt
	./lab5 in54.txt > ans.txt && diff out54.txt ans.txt
	./lab5 in55.txt > ans.txt && diff out55.txt ans.txt
	./lab5 in56.txt > ans.txt && diff out56.txt ans.txt
	./lab5 in58.txt > ans.txt && diff out58.txt ans.txt
	./lab5 in59.txt > ans.txt && diff out59.txt ans.txt
	./lab5 in61.txt > ans.txt && diff out61.txt ans.txt
	./lab5 in62.txt > ans.txt && diff out62.txt ans.txt
	./lab5 in64.txt > ans.txt && diff out64.txt ans.txt

test:
	g++ -Wall -Werror -std=c++17 -g *.cpp *.h -o lab5
	./lab5 test.txt